spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

dox:
  security:
    jwt-signing-key: ${JWT_SECRET}
  hsts:
    enabled: false

springdoc:
  api-docs:
    enabled: true

scalar:
  enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
