server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: DOX Backend
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  profiles:
    active: local

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
    doc-expansion: none
  api-docs:
    path: /v3-docs
