ALTER TABLE report_templates ADD COLUMN IF NOT EXISTS is_locked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE report_templates ADD COLUMN IF NOT EXISTS is_master BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE reports ADD COLUMN IF NOT EXISTS template_id UUID REFERENCES report_templates(id) ON DELETE SET NULL;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS is_structure_locked BOOLEAN NOT NULL DEFAULT FALSE;

