CREATE TABLE content_library (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title      VARCHAR(300) NOT NULL,
    content    JSONB        NOT NULL,
    type       VARCHAR(50)  NOT NULL DEFAULT 'reference',
    category   VARCHAR(50)  NOT NULL DEFAULT 'general',
    instrument VARCHAR(200),
    authors    VARCHAR(500),
    year       INTEGER,
    tags       VARCHAR(500),
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now()
);

-- Referências bibliográficas (type=reference)
INSERT INTO content_library (title, content, type, category, instrument, authors, year) VALUES
('WAIS-III', '[{"type":"p","children":[{"text":"WECHSLER, D. ","bold":true},{"text":"Escala de Inteligência Wechsler para Adultos 3ª. Edição – WAIS III.","italic":true},{"text":" São Paulo: Pearson, 2017."}]}]'::JSONB, 'reference', 'instrument', 'WAIS-III', 'Wechsler', 2017),
('RAVLT', '[{"type":"p","children":[{"text":"D''PAULA, J. J.; MALLOY-DINIZ, L. F. ","bold":true},{"text":"Teste de Aprendizagem Auditivo-Verbal de Rey – RAVLT.","italic":true},{"text":" São Paulo: Vetor, 2018."}]}]'::JSONB, 'reference', 'instrument', 'RAVLT', 'D''Paula, Malloy-Diniz', 2018),
('Figuras Complexas de Rey', '[{"type":"p","children":[{"text":"REY, A. ","bold":true},{"text":"Figuras Complexas de Rey – Teste de Cópia e de Reprodução de Memória de Figuras Geométricas Complexas.","italic":true},{"text":" 2. ed. São Paulo: Pearson, 2014."}]}]'::JSONB, 'reference', 'instrument', 'Figuras Complexas de Rey', 'Rey', 2014),
('BPA-2', '[{"type":"p","children":[{"text":"RUEDA, F. J. M. ","bold":true},{"text":"Bateria Psicológica para Avaliação da Atenção – BPA-2.","italic":true},{"text":" São Paulo: Vetor, 2022."}]}]'::JSONB, 'reference', 'instrument', 'BPA-2', 'Rueda', 2022),
('FDT', '[{"type":"p","children":[{"text":"SEDÓ, M.; PAULA, J. J.; MALLOY-DINIZ, L. F. ","bold":true},{"text":"O teste dos cinco dígitos – FDT – Five Digit Test.","italic":true},{"text":" São Paulo: Hogrefe CETEPP, 2015."}]}]'::JSONB, 'reference', 'instrument', 'FDT', 'Sedó, Paula, Malloy-Diniz', 2015),
('IFP-II', '[{"type":"p","children":[{"text":"ALVES, I. C. B.; LEMES, L. S.; RABELO, I. S. ","bold":true},{"text":"Inventário Fatorial de Personalidade – IFP-II.","italic":true},{"text":" São Paulo: Editora Pearson, 2019."}]}]'::JSONB, 'reference', 'instrument', 'IFP-II', 'Alves, Lemes, Rabelo', 2019),
('ETDAH-AD', '[{"type":"p","children":[{"text":"BENCZIK, E. B. P. ","bold":true},{"text":"Escala de Avaliação de Transtorno de Déficit de Atenção e Hiperatividade – Versão Adolescentes e Adultos – ETDAH-AD.","italic":true},{"text":" 1. ed. São Paulo: Vetor, 2013."}]}]'::JSONB, 'reference', 'instrument', 'ETDAH-AD', 'Benczik', 2013),
('SRS-2', '[{"type":"p","children":[{"text":"GRUBER, C. P.; CONSTANTINO, J. N. ","bold":true},{"text":"Escala de Responsividade Social – SRS-2.","italic":true},{"text":" São Paulo: Hogrefe CETEPP, 2021."}]}]'::JSONB, 'reference', 'instrument', 'SRS-2', 'Gruber, Constantino', 2021),
('ToL-BR', '[{"type":"p","children":[{"text":"SERPA, A. ","bold":true},{"text":"et al.","italic":true},{"text":" ","bold":true},{"text":"Torre de Londres – ToL-BR.","italic":true},{"text":" São Paulo: Vetor, 2023."}]}]'::JSONB, 'reference', 'instrument', 'ToL-BR', 'Serpa, Timóteo, Oliveira, Querino, Malloy-Diniz', 2023),
('Guia Escalas Wechsler', '[{"type":"p","children":[{"text":"PESSOTTO, F.; BARTHOLOMEU, D. ","bold":true},{"text":"Guia prático das Escalas Wechsler: uso e análise das escalas WISCIV, WAIS-III e WASI.","italic":true},{"text":" São Paulo: Pearson Clinical Brasil, 2019."}]}]'::JSONB, 'reference', 'instrument', 'WAIS-III, WISCIV, WASI', 'Pessotto, Bartholomeu', 2019),
('Funções Executivas — Brião', '[{"type":"p","children":[{"text":"BRIÃO, J. C.; CAMPANHOLO, K. R. ","bold":true},{"text":"Funções executivas. "},{"text":"In:","italic":true},{"text":" MIOTTO, E. C. "},{"text":"et al.","italic":true},{"text":" "},{"text":"Manual de Avaliação Neuropsicológica.","italic":true},{"text":" São Paulo: Memnon, 2018. v. 1."}]}]'::JSONB, 'reference', 'general', 'Funções Executivas', 'Brião, Campanholo', 2018),
('Funções Executivas — Cardoso', '[{"type":"p","children":[{"text":"CARDOSO, C. O. ","bold":true},{"text":"et al.","italic":true},{"text":" Funções executivas e regulação emocional: intervenções e implicações educacionais. "},{"text":"In:","italic":true},{"text":" DIAS, N. M.; MECCA, T. "},{"text":"Contribuições da neuropsicologia e da psicologia para intervenção no contexto educacional.","italic":true},{"text":" São Paulo: Memnon, 2015."}]}]'::JSONB, 'reference', 'general', 'Funções Executivas', 'Cardoso, Pureza, Gonçalves, Fonseca', 2015),
('Executive Functions — Diamond', '[{"type":"p","children":[{"text":"DIAMOND, A. ","bold":true},{"text":"Executive functions. "},{"text":"Annual Review of Psychology,","italic":true},{"text":" v. 64, p. 135-168, 2013."}]}]'::JSONB, 'reference', 'general', 'Funções Executivas', 'Diamond', 2013),
('Avaliação Neuropsicológica — Malloy-Diniz', '[{"type":"p","children":[{"text":"MALLOY-DINIZ, L. F. ","bold":true},{"text":"et al.","italic":true},{"text":" "},{"text":"Avaliação neuropsicológica.","italic":true},{"text":" Porto Alegre: Artmed, 2010."}]}]'::JSONB, 'reference', 'general', NULL, 'Malloy-Diniz', 2010),
('Funções Executivas — Malloy-Diniz', '[{"type":"p","children":[{"text":"MALLOY-DINIZ, L. F. ","bold":true},{"text":"et al.","italic":true},{"text":" Neuropsicologia das funções executivas e da atenção. "},{"text":"In:","italic":true},{"text":" FUENTES, D. "},{"text":"et al.","italic":true},{"text":" (Org.). "},{"text":"Neuropsicologia: Teoria e Prática.","italic":true},{"text":" 2. ed. Porto Alegre: Artmed, 2014."}]}]'::JSONB, 'reference', 'general', 'Funções Executivas', 'Malloy-Diniz, De Paula, Sedó, Fuentes, Leite', 2014),
('Instinto da Linguagem — Pinker', '[{"type":"p","children":[{"text":"PINKER, S. ","bold":true},{"text":"O Instinto da Linguagem: como a mente cria a linguagem.","italic":true},{"text":" São Paulo: Editora Martins Fontes, 2002."}]}]'::JSONB, 'reference', 'general', 'Linguagem', 'Pinker', 2002),
('Pensamento — Pinker', '[{"type":"p","children":[{"text":"PINKER, S. ","bold":true},{"text":"Do que é feito o pensamento: a língua como janela para a natureza humana.","italic":true},{"text":" São Paulo: Companhia das Letras, 2008."}]}]'::JSONB, 'reference', 'general', 'Linguagem', 'Pinker', 2008),
('Criatividade — Hu e Adey', '[{"type":"p","children":[{"text":"HU, W.; ADEY, P. ","bold":true},{"text":"Avaliação de traços, processos cognitivos e produtos científico-criativos.","italic":true},{"text":" 2002."}]}]'::JSONB, 'reference', 'general', 'Criatividade', 'Hu, Adey', 2002),
('Teste dos Cinco Pontos', '[{"type":"p","children":[{"text":"BARTHOLOMEU, D.; PESSOTTO, F. ","bold":true},{"text":"et al.","italic":true},{"text":" "},{"text":"Teste dos Cinco Pontos.","italic":true},{"text":" São Paulo: Pearson, 2019."}]}]'::JSONB, 'reference', 'instrument', 'Teste dos Cinco Pontos', 'Bartholomeu, Pessotto', 2019);

-- Descrições de instrumentos (type=instrument)
INSERT INTO content_library (title, content, type, category, instrument, tags) VALUES
('WAIS-III — Descrição', '[{"type":"p","children":[{"text":"A "},{"text":"Escala de Inteligência Wechsler para Adultos — terceira edição (WAIS-III)","bold":true},{"text":" constitui uma bateria de avaliação intelectual de amplo espectro, desenvolvida originalmente por David Wechsler. No contexto da avaliação neuropsicológica, permite a mensuração de funções cognitivas como raciocínio verbal, organização perceptual, memória operacional e velocidade de processamento, por meio de subtestes padronizados com normatização para a população brasileira."}]}]'::JSONB, 'instrument', 'instrument', 'WAIS-III', 'inteligência, eficiência cognitiva, QI'),
('RAVLT — Descrição', '[{"type":"p","children":[{"text":"O "},{"text":"Teste de Aprendizagem Auditivo-Verbal de Rey (RAVLT)","bold":true},{"text":" é um instrumento neuropsicológico voltado à avaliação da "},{"text":"memória episódica verbal","italic":true},{"text":", abrangendo processos de aprendizagem, evocação imediata, evocação tardia e reconhecimento. O teste consiste na apresentação de uma lista de 15 palavras ao longo de cinco tentativas, permitindo a construção de uma curva de aprendizagem e a análise de efeitos de interferência proativa e retroativa."}]}]'::JSONB, 'instrument', 'instrument', 'RAVLT', 'memória, aprendizagem'),
('FDT — Descrição', '[{"type":"p","children":[{"text":"O "},{"text":"Five Digit Test (FDT)","bold":true},{"text":" é um instrumento neuropsicológico que avalia funções executivas relacionadas à atenção, com ênfase na "},{"text":"velocidade de processamento","italic":true},{"text":", "},{"text":"atenção seletiva","italic":true},{"text":" e "},{"text":"controle inibitório","italic":true},{"text":". É estruturado em quatro condições progressivamente mais complexas: Leitura, Contagem, Escolha e Alternância, sendo registrados tempo de execução e número de erros em cada condição."}]}]'::JSONB, 'instrument', 'instrument', 'FDT', 'atenção, funções executivas, controle inibitório'),
('BPA-2 — Descrição', '[{"type":"p","children":[{"text":"A "},{"text":"Bateria Psicológica para Avaliação da Atenção (BPA-2)","bold":true},{"text":" é um instrumento padronizado para avaliar a capacidade de "},{"text":"atenção concentrada","italic":true},{"text":", "},{"text":"alternada","italic":true},{"text":" e "},{"text":"dividida","italic":true},{"text":". Permite a obtenção de um escore de atenção geral, além dos escores específicos por modalidade atencional, com normatização para a população brasileira."}]}]'::JSONB, 'instrument', 'instrument', 'BPA-2', 'atenção'),
('Figuras Complexas de Rey — Descrição', '[{"type":"p","children":[{"text":"O teste das "},{"text":"Figuras Complexas de Rey","bold":true},{"text":" avalia "},{"text":"planejamento","italic":true},{"text":", "},{"text":"organização visuoespacial","italic":true},{"text":", "},{"text":"memória visual imediata","italic":true},{"text":" e "},{"text":"capacidade perceptiva","italic":true},{"text":". O examinando realiza a cópia de uma figura geométrica complexa e, após intervalo, reproduz a mesma figura de memória, permitindo a análise das estratégias de planejamento e da retenção visual."}]}]'::JSONB, 'instrument', 'instrument', 'Figuras Complexas de Rey', 'percepção, memória visual, planejamento'),
('IFP-II — Descrição', '[{"type":"p","children":[{"text":"O "},{"text":"Inventário Fatorial de Personalidade (IFP-II)","bold":true},{"text":" tem por objetivo traçar o perfil da personalidade do indivíduo com base em 13 necessidades ou motivos psicológicos, incluindo: assistência, intracepção, afago, deferência, afiliação, dominância, desempenho, exibição, agressão, ordem, persistência, mudança e autonomia."}]}]'::JSONB, 'instrument', 'instrument', 'IFP-II', 'personalidade'),
('ETDAH-AD — Descrição', '[{"type":"p","children":[{"text":"A "},{"text":"Escala de Transtorno do Déficit de Atenção e Hiperatividade — Versão Adolescentes e Adultos (ETDAH-AD)","bold":true},{"text":" tem como objetivo verificar sintomas envolvidos no TDAH por meio do autorrelato, avaliando fatores de "},{"text":"desatenção","italic":true},{"text":", "},{"text":"impulsividade","italic":true},{"text":", "},{"text":"aspectos emocionais","italic":true},{"text":", autorregulação da atenção e "},{"text":"hiperatividade","italic":true},{"text":"."}]}]'::JSONB, 'instrument', 'instrument', 'ETDAH-AD', 'TDAH, atenção'),
('SRS-2 — Descrição', '[{"type":"p","children":[{"text":"A "},{"text":"Escala de Responsividade Social (SRS-2)","bold":true},{"text":" tem como objetivo mensurar sintomas associados ao "},{"text":"Transtorno do Espectro Autista (TEA)","italic":true},{"text":", classificando-os em níveis leves, moderados ou severos. A avaliação é realizada por meio do autorrelato e heterorrelato, abrangendo subescalas de percepção social, cognição social, comunicação social, motivação social e padrões restritos e repetitivos."}]}]'::JSONB, 'instrument', 'instrument', 'SRS-2', 'TEA, autismo, cognição social'),
('ToL-BR — Descrição', '[{"type":"p","children":[{"text":"A "},{"text":"Torre de Londres (ToL-BR)","bold":true},{"text":" é um instrumento neuropsicológico que avalia "},{"text":"planejamento","italic":true},{"text":", "},{"text":"resolução de problemas","italic":true},{"text":" e "},{"text":"funções executivas","italic":true},{"text":". O teste requer que o examinando reproduza configurações de esferas coloridas em pinos, planejando antecipadamente a sequência de movimentos necessários, em número mínimo de jogadas."}]}]'::JSONB, 'instrument', 'instrument', 'ToL-BR', 'funções executivas, planejamento');

-- Bases conceituais (type=procedure)
INSERT INTO content_library (title, content, type, category, tags) VALUES
('Base conceitual — Atenção e Velocidade de Processamento', '[{"type":"p","children":[{"text":"A "},{"text":"velocidade de processamento","bold":true},{"text":" é definida como a capacidade mental de processar rapidamente uma informação: codificar, transformar e recuperar (Lambert; Spinath, 2017; Passolunghi; Lanfranchi, 2012). Prestar atenção significa detectar mudanças no meio externo, deter-se sobre elas e, ao mesmo tempo, inibir a interferência de outros estímulos concorrentes (Posner e Raichle, 1994). A "},{"text":"atenção","bold":true},{"text":" é uma habilidade multidimensional, cujos componentes misturam-se a outras habilidades, como a memória e as funções executivas, tornando-se uma habilidade difícil de avaliar isoladamente. A "},{"text":"atenção seletiva","italic":true},{"text":" refere-se à capacidade de focalizar um estímulo específico em detrimento de distratores. A "},{"text":"alternância","italic":true},{"text":" corresponde à capacidade de alternar entre um estímulo e outro. A "},{"text":"sustentação","italic":true},{"text":" corresponde à capacidade de manter o foco atentivo em uma determinada atividade por um tempo mais prolongado. A "},{"text":"atenção dividida","italic":true},{"text":" refere-se à distribuição de recursos de atenção para mais de um estímulo simultaneamente (Gonçalves, Cardoso, Pureza & Scheffer, 2020)."}]}]'::JSONB, 'procedure', 'general', 'atenção, velocidade de processamento'),
('Base conceitual — Memória', '[{"type":"p","children":[{"text":"A "},{"text":"memória","bold":true},{"text":" é o mecanismo na qual ocorre a aquisição, retenção, armazenamento e recuperação das informações obtidas pelas experiências diárias (Lent, 2001). De acordo com o tempo de retenção ou duração, pode-se dividi-la em "},{"text":"memória de curto prazo","bold":true},{"text":" ou "},{"text":"memória de longo prazo","bold":true},{"text":". A primeira refere-se aos primeiros segundos ou minutos até 6 horas após a retenção da informação. A "},{"text":"memória de longo prazo","italic":true},{"text":" pode ser dividida em "},{"text":"memória declarativa ou explícita","italic":true},{"text":" e "},{"text":"memória não declarativa ou implícita","italic":true},{"text":". A "},{"text":"memória episódica","italic":true},{"text":" lida com eventos específicos, pessoais e datados temporalmente. A "},{"text":"memória semântica","italic":true},{"text":" refere-se ao conhecimento sobre o mundo. A "},{"text":"memória operacional ou memória de trabalho","bold":true},{"text":" permite manter e manipular informações a curto prazo a fim de fazer algo (Izquierdo, 2018)."}]}]'::JSONB, 'procedure', 'general', 'memória'),
('Base conceitual — Funções Executivas', '[{"type":"p","children":[{"text":"As "},{"text":"funções executivas","bold":true},{"text":" consistem em um conjunto de processos cognitivos que, de forma integrada, permitem ao indivíduo direcionar comportamentos a metas, avaliar eficiência e adequação desses comportamentos, abandonar estratégias ineficazes e resolver problemas imediatos, de médio e de longo prazo (Malloy-Diniz et al., 2008). Envolvem: "},{"text":"memória operacional","italic":true},{"text":" — manter e manipular informações; "},{"text":"controle inibitório","italic":true},{"text":" — inibir comportamentos inapropriados e manter o foco atencional; "},{"text":"flexibilidade cognitiva","italic":true},{"text":" — mudar perspectivas e estratégias; "},{"text":"planejamento","italic":true},{"text":" — estabelecer etapas para alcançar objetivos; "},{"text":"tomada de decisão","italic":true},{"text":" — escolher entre alternativas; "},{"text":"categorização","italic":true},{"text":" — agrupar elementos por propriedades; "},{"text":"fluência","italic":true},{"text":" — emitir comportamentos em sequência obedecendo a regras; e "},{"text":"autorregulação","italic":true},{"text":" — monitoração do desempenho efetivo (Diamond, 2013)."}]}]'::JSONB, 'procedure', 'general', 'funções executivas');
