ALTER TABLE customer_notes ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE customer_events ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE customer_events ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();
